server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: zhuoer93-
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: REWARD_MANAGER
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



